### ISSUE TITLE
Connectors will be replaced by Workflows

### ISSUE THREAD

**Issue by flame-zh** [cmdisp/monolog-microsoft-teams#16]
Hello,

As I mentioned in the title, Teams Connectors are being replaced by Teams Workflows.

I started to receive these messages:

> Action Required:
> O365 connectors within Teams will be deprecated and notifications from this service will stop.
> [Learn more](https://aka.ms/O365ConnectorDeprecation) about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request.

Unfortunately the new URLs don't work with this repository. Are there any plans to update this repository before 1 October 2024, when Connectors stop working?

**Comment by kvdbergh** [comment]
Hi @flame-zh, there are no plans to update this repository to support Power Automate workflows.
