### ISSUE TITLE
Not upgradeble via Composer?

### ISSUE THREAD

**Issue by germania-kg** [cmdisp/monolog-microsoft-teams#4]
Can't upgrade to the 1.1 release with PHP7.2. **composer.json:**
```json
"require": {
   "cmdisp/monolog-microsoft-teams": "^1.1"        
}
```

```
Problem 1
    - The requested package cmdisp/monolog-microsoft-teams ^1.1 exists as cmdisp/monolog-microsoft-teams[1.0.0, dev-master] but these are rejected by your constraint.
````

The corresponding [packagist site](https://packagist.org/packages/cmdisp/monolog-microsoft-teams) still shows the v1.0. It seems the latest version tag 1.1 did not find its way.

**Comment by kvdbergh** [comment]
The package was using a legacy service integration and could not auto-update. The package has now been updated to version 1.1

**Comment by germania-kg** [comment]
I suspected something like that. Thanks a lot, Kevin!

**Comment by tomkyle** [comment]
For 1.2.0, it seems packagist has not been updated – possibly due to the mentioned legacy thingy... Can someone have a look?

**Comment by kvdbergh** [comment]
Version 1.2.0 is now available on packagist.
