### ISSUE TITLE
Totality of error message content is not showed

### ISSUE THREAD

**Issue by hamdigaied** [cmdisp/monolog-microsoft-teams#5]
The log of error message content is not showed totally only the first part of it.

![image](https://user-images.githubusercontent.com/33940594/91158990-5bb5bb00-e6bf-11ea-873a-d7390d56f2e8.png)

Is there a solution for that ?

**Comment by kvdbergh** [comment]
This is because the error stack trace is not added by default to the formatted message. It is possible to set a custom log formatter: https://laravel.com/docs/8.x/logging#customizing-monolog-for-channels
